name: WordPress Auto Post

on:
  schedule:
    - cron: '0 4 * * *'   # 한국시간 오후 1시
    - cron: '0 8 * * *'   # 한국시간 오후 5시
    - cron: '0 10 * * *'  # 한국시간 오후 7시
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run auto post script
      run: python blog.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        WP_URL: ${{ secrets.WP_URL }}
        WP_USERNAME: ${{ secrets.WP_USERNAME }}
        WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
        CP_ACCESS_KEY: ${{ secrets.CP_ACCESS_KEY }}
        CP_SECRET_KEY: ${{ secrets.CP_SECRET_KEY }}
        PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
