name: WordPress Auto Post

on:
  schedule:
    - cron: '0 */6 * * *'  # 매 6시간마다 실행
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run auto post script
      run: python blog.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        WP_URL: ${{ secrets.WP_URL }}
        WP_USERNAME: ${{ secrets.WP_USERNAME }}
        WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
        CP_ACCESS_KEY: ${{ secrets.CP_ACCESS_KEY }}
        CP_SECRET_KEY: ${{ secrets.CP_SECRET_KEY }}
   
   - name: Run jb.py (트렌드 자동 뉴스 포스팅)
      run: python jb.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        WP_URL: ${{ secrets.WP_URL }}
        WP_USERNAME: ${{ secrets.WP_USERNAME }}
        WP_PASSWORD: ${{ secrets.WP_PASSWORD }}

